### ISSUE TITLE
Free monad?

### ISSUE THREAD

**Issue by rlecomte** [travisbrown/circe-algebra#1]
I'm very interested in your work here. So i look the code and be a little bit confuse about your algebra and interpreter. It look like Free monad. Why not using the cats implementation? What is your idea behind that?

**Comment by travisbrown** [comment]
Yes, we could definitely use `Free` here. The problem is that `Free` imposes at least one extra layer everywhere, and one of the goals of this project is to maintain the performance we currently have with cursors.

We did something similar in catbird, where `Rerunnable` is essentially just a `Free[Future, ?]`, but using `Free[Future, ?]` directly is both slightly less convenient and involves many more allocations (I've got benchmarks somewhere—I'll try to find them and link them here).

`Free` is great for application code and for algebras in libraries that are intended to be extended by users, but it's not the only way to represent operations as data, and for an internal piece of a library (which is more or less what this is intended to be), it's not necessarily ideal—in my view this is a place where the cost of baking a `Bind` into the algebra is totally reasonable.

**Comment by travisbrown** [comment]
Here's a comparison that's currently available in the `benchmarks` project. Note that the `Free` implementation doesn't provide all of the functionality of the other approaches (no history, etc.), but is still an order of magnitude slower.

```
Benchmark                                        Mode  Cnt       Score       Error  Units
DecodingBenchmark.decodeFailFastWithCursors      avgt   40   27451.969 ±   908.135  ns/op
DecodingBenchmark.decodeFailFastWithHistory      avgt   40   22264.036 ±   307.020  ns/op
DecodingBenchmark.decodeFailFast                 avgt   40   22345.150 ±   504.217  ns/op

DecodingBenchmark.decodeAccumulatingWithCursors  avgt   40   25655.904 ±   273.102  ns/op
DecodingBenchmark.decodeAccumulatingWithHistory  avgt   40   21782.556 ±   319.385  ns/op
DecodingBenchmark.decodeAccumulating             avgt   40   21871.921 ±   200.179  ns/op

DecodingBenchmark.decodeFree                     avgt   40  472770.919 ± 12925.517  ns/op
```
